/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import ir.Document;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.Map;
import java.util.Scanner;
import java.util.Set;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;
import javax.swing.table.DefaultTableModel;
import ir.BooleanModel;
import java.util.HashMap;

/**
 *
 * @author mosta
 */
public class main extends javax.swing.JFrame {

    ArrayList<Document> allDocs;
    Map<String, String> matrix;
    DefaultTableModel Table_Program1_model, Table_Program2_model;
    BooleanModel booleanModel;

    //DocumentMatrix Matrix;
    //DocumentSet Set;
    /**
     * Creates new form main
     */
    public main() {

        allDocs = new ArrayList<>();
        matrix = new HashMap<>();
        booleanModel = new BooleanModel();
        initComponents();
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            @Override
            public int getSize() {
                return allDocs.size();
            }

            @Override
            public String getElementAt(int i) {
                return allDocs.get(i).getName();
            }
        });
        Table_Program2_model = new DefaultTableModel(new Object[][]{}, new String[]{"Term", "Boolean vector"}) {
            Class[] types = new Class[]{java.lang.String.class, java.lang.String.class};
            boolean[] canEdit = new boolean[]{false, false};

            @Override
            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        };
        Table_Program2.setModel(Table_Program2_model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        btn_AddDoc = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel7 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TA_Doc = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        TA_Tokens = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        TF_Program2_Query = new javax.swing.JTextField();
        Btn_Program2_Search = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        Table_Program2 = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TF_Bitwise_function = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        TA_Program2_Result = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel6.setPreferredSize(new java.awt.Dimension(200, 290));
        jPanel6.setLayout(new java.awt.BorderLayout());

        btn_AddDoc.setText("Add Document");
        btn_AddDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AddDocActionPerformed(evt);
            }
        });
        jPanel6.add(btn_AddDoc, java.awt.BorderLayout.NORTH);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jList1);

        jPanel6.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel6, java.awt.BorderLayout.WEST);

        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel4.setMaximumSize(new java.awt.Dimension(32767, 23));
        jPanel4.setMinimumSize(new java.awt.Dimension(1, 1));
        jPanel4.setPreferredSize(new java.awt.Dimension(460, 23));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Document");
        jPanel4.add(jLabel6, java.awt.BorderLayout.CENTER);

        jPanel7.add(jPanel4);

        TA_Doc.setColumns(20);
        TA_Doc.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        TA_Doc.setRows(5);
        TA_Doc.setToolTipText("Document");
        jScrollPane3.setViewportView(TA_Doc);

        jPanel7.add(jScrollPane3);

        jPanel5.setMaximumSize(new java.awt.Dimension(32767, 23));
        jPanel5.setMinimumSize(new java.awt.Dimension(1, 1));
        jPanel5.setPreferredSize(new java.awt.Dimension(460, 23));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Tokens");
        jPanel5.add(jLabel7, java.awt.BorderLayout.CENTER);

        jPanel7.add(jPanel5);

        TA_Tokens.setColumns(20);
        TA_Tokens.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        TA_Tokens.setLineWrap(true);
        TA_Tokens.setRows(5);
        TA_Tokens.setToolTipText("Tokens");
        TA_Tokens.setWrapStyleWord(true);
        jScrollPane4.setViewportView(TA_Tokens);

        jPanel7.add(jScrollPane4);

        jPanel1.add(jPanel7, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Documents", jPanel1);

        TF_Program2_Query.setToolTipText("Query");
        TF_Program2_Query.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_Program2_QueryActionPerformed(evt);
            }
        });

        Btn_Program2_Search.setText("Search");
        Btn_Program2_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Program2_SearchActionPerformed(evt);
            }
        });

        jPanel8.setLayout(new java.awt.GridLayout(1, 5));

        Table_Program2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(Table_Program2);

        jPanel8.add(jScrollPane5);

        jLabel1.setText("Bitwise function :-");

        TF_Bitwise_function.setEditable(false);

        jLabel2.setText("Matched Documents :-");

        TA_Program2_Result.setEditable(false);
        TA_Program2_Result.setColumns(20);
        TA_Program2_Result.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        TA_Program2_Result.setRows(5);
        jScrollPane6.setViewportView(TA_Program2_Result);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(140, Short.MAX_VALUE))
                    .addComponent(TF_Bitwise_function)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(5, 5, 5)
                .addComponent(TF_Bitwise_function, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE))
        );

        jPanel8.add(jPanel9);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(TF_Program2_Query)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Btn_Program2_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TF_Program2_Query, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Program2_Search))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("BooleanModel", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_AddDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AddDocActionPerformed
        JFileChooser open = new JFileChooser();
        open.setDialogTitle("Choose a text file");
        open.setDialogType(JFileChooser.OPEN_DIALOG);
        open.setMultiSelectionEnabled(true);
        open.addChoosableFileFilter(new FileFilter() {
            @Override
            public boolean accept(File f) {
                return f.isDirectory() || f.getAbsolutePath().toLowerCase().endsWith(".txt");
            }

            @Override
            public String getDescription() {
                return "Text files only(.txt)";
            }
        });
        open.setAcceptAllFileFilterUsed(false);
        open.setFileSelectionMode(JFileChooser.FILES_ONLY);
        if (open.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            try {
                for (File selectedFile : open.getSelectedFiles()) {
                    Scanner reader = new Scanner(selectedFile);
                    reader.useDelimiter("\\A");
                    Document d = new Document(selectedFile.getName(), reader.hasNext() ? reader.next() : "");
                    allDocs.add(d);
                    //Matrix.addDocument(d);
                    //Set.addDocument(d);
                    jList1.updateUI();
                }
            } catch (FileNotFoundException ex) {
            }
        }
    }//GEN-LAST:event_btn_AddDocActionPerformed

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        if (evt.getValueIsAdjusting()) {
            Document d = allDocs.get(jList1.getSelectedIndex());
            TA_Doc.setText(d.getText());
            TA_Tokens.setText(d.getTokens() + "");
        }
    }//GEN-LAST:event_jList1ValueChanged

    private void TF_Program2_QueryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_Program2_QueryActionPerformed
        Btn_Program2_Search.doClick();
    }//GEN-LAST:event_TF_Program2_QueryActionPerformed

    private void Btn_Program2_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Program2_SearchActionPerformed
        if (TF_Program2_Query.getText().equals("")) {
        } else {
            String result = booleanModel.QueryResult(allDocs, TF_Program2_Query.getText());           
            TF_Bitwise_function.setText(result.isEmpty() ? "" :result.replaceAll(".", "$0 ") );
            String data = "";
            
             ArrayList<Document> DocNames=booleanModel.GetDocumnetsNames(allDocs);
             
            if (DocNames.isEmpty()) {
                data = "No matched documents !";
            }
            for (int i = 0; i < DocNames.size(); i++) {
                data += 1 + i + " - " + DocNames.get(i).getName()+ "\n";
            }
            TA_Program2_Result.setText(data);
        }
    }//GEN-LAST:event_Btn_Program2_SearchActionPerformed

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked

        if (jTabbedPane1.getSelectedIndex() == 1) {
            Table_Program2_model.setRowCount(0);
            TA_Program2_Result.setText(" ");
            TF_Bitwise_function.setText(" ");
            matrix = booleanModel.getMatrix(allDocs);
            //System.out.println(matrix);
            for (Map.Entry<String, String> entry : matrix.entrySet()) {
                Table_Program2_model.addRow(new String[]{entry.getKey(), entry.getValue().replaceAll(".", "$0   ")});
                //System.out.println(entry.getKey() + " : " + entry.getValue());
            }

        }
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Program2_Search;
    private javax.swing.JTextArea TA_Doc;
    private javax.swing.JTextArea TA_Program2_Result;
    private javax.swing.JTextArea TA_Tokens;
    private javax.swing.JTextField TF_Bitwise_function;
    private javax.swing.JTextField TF_Program2_Query;
    private javax.swing.JTable Table_Program2;
    private javax.swing.JButton btn_AddDoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
